# Generated by Django 3.1.7 on 2021-06-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20210412_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'permissions': [('can_view_items', 'Can view items'), ('can_add_items', 'Can add items'), ('can_update_items', 'Can update items'), ('can_delete_items', 'Can delete items')]},
        ),
    ]
